Repository COSC481W-2022Fall/capstone-project-stuff-stash, pull requests merged in 2022-12, with the labels that each got.

#72 Bug:Logout button not working
  Stuff-Stash/client/src/Pages/dashboard.js
Labels: bug, sprint3

#73 62 list users in organization arie
  Stuff-Stash/client/src/App.js
  Stuff-Stash/client/src/Pages/dashboard.js
  Stuff-Stash/client/src/Pages/viewOrgMembers.js
  Stuff-Stash/client/src/components/ViewMembers.jsx
  Stuff-Stash/server/index.js
Labels: Feature, Backend, sprint3

#75 FEAT: removing optional org ID on registrationform
  Stuff-Stash/client/src/components/registrationform.jsx
Labels: enhancement, Feature, Frontend, Maintenance, sprint3

#76 feat: Ability to view assets under the stockroom you click
  Stuff-Stash/client/src/components/StockRoomViewDashboard.jsx
  Stuff-Stash/client/src/components/assetCard.jsx
  Stuff-Stash/client/src/components/orgView.jsx
  Stuff-Stash/server/index.js
Labels: enhancement, Feature, Backend, Maintenance, sprint3

#79 51 delete asset hussein madeline arie
  Stuff-Stash/client/src/components/assetCard.jsx
  Stuff-Stash/client/src/components/styles/assetCard.css
  Stuff-Stash/client/src/utils/UpdateForm.jsx
  Stuff-Stash/server/index.js
Labels: Feature, Frontend, Backend, sprint3

#80 58 create asset dynamically sean lynaa niveetha
  Stuff-Stash/client/src/Pages/addAssetForm.js
  Stuff-Stash/client/src/components/StockRoomViewDashboard.jsx
  Stuff-Stash/server/index.js
Labels: enhancement, Frontend, Backend

#81 Feature: Ability to edit and update Assets
  Stuff-Stash/client/src/Pages/dashboard.js
  Stuff-Stash/client/src/Pages/styles/dashboardStyles.css
  Stuff-Stash/client/src/components/assetCard.jsx
  Stuff-Stash/client/src/utils/UpdateForm.jsx
  Stuff-Stash/server/index.js
Labels: Feature, Frontend, Backend, sprint3

#82 55- Ability to delete stockrooms
  Stuff-Stash/client/package-lock.json
  Stuff-Stash/client/src/components/StockRoomViewDashboard.jsx
  Stuff-Stash/server/index.js
  Stuff-Stash/server/package-lock.json
  Stuff-Stash/server/package.json
Labels: Feature, Frontend, Backend, sprint3

#83 60 Asset Cards Matt Lynaa
  Stuff-Stash/client/src/App.css
  Stuff-Stash/client/src/App.js
  Stuff-Stash/client/src/Pages/dashboard.js
  Stuff-Stash/client/src/Pages/styles/dashboardStyles.css
  Stuff-Stash/client/src/Pages/styles/scrollbarStyle.css
  Stuff-Stash/client/src/components/StockRoomViewDashboard.jsx
  Stuff-Stash/client/src/components/assetCard.jsx
  Stuff-Stash/client/src/components/styles/assetCard.css
  Stuff-Stash/client/src/index.js
Labels: Feature, Frontend
