Repository COSC481W-2022Fall/capstone-project-stuff-stash, pull requests merged in 2022-11, with the labels that each got.

#39 Enhancement: Changed the function to accept multiple organizations for a user
  Stuff-Stash/server/index.js
  Stuff-Stash/server/models/user.js
  Stuff-Stash/server/package-lock.json
  Stuff-Stash/server/package.json
Labels: enhancement, sprint2

#44 Create asset backend sean hussein
  .env
  Stuff-Stash/server/index.js
  Stuff-Stash/server/models/Asset.js
  Stuff-Stash/server/models/stockroom.js
  node_modules/.package-lock.json
  package-lock.json
  package.json
Labels: Feature, sprint2, Backend

#45 20 move existing functionality to dashboard matt sean
  .vscode/tasks.json
  Stuff-Stash/client/src/App.js
  Stuff-Stash/client/src/Pages/CreateStockRoom.js
  Stuff-Stash/client/src/Pages/dashboard.js
  Stuff-Stash/client/src/components/CreateOrg.jsx
  Stuff-Stash/server/index.js
Labels: enhancement, sprint2, Frontend

#46 19 create asset frontend sean madeline
  Stuff-Stash/client/src/App.js
  Stuff-Stash/client/src/Pages/CreateStockRoom.js
  Stuff-Stash/client/src/Pages/addAssetForm.js
  Stuff-Stash/client/src/Pages/dashboard.js
Labels: Feature, sprint2, Frontend

#53 49 chore cleanup front end files matt
  Stuff-Stash/client/src/App.css
  Stuff-Stash/client/src/App.js
  Stuff-Stash/client/src/Pages/AddUserOrg.js
  Stuff-Stash/client/src/Pages/CreateStockRoom.js
  Stuff-Stash/client/src/Pages/Home.js
  Stuff-Stash/client/src/Pages/ListOfUsers.js
  Stuff-Stash/client/src/Pages/RenameOrg.js
  Stuff-Stash/client/src/Pages/addAssetForm.js
  Stuff-Stash/client/src/Pages/dashboard.js
  Stuff-Stash/client/src/Pages/login.js
  Stuff-Stash/client/src/Pages/navbar.js
  Stuff-Stash/client/src/Pages/styles/dashboardStyles.css
  Stuff-Stash/client/src/Pages/viewstockroomFrontend.js
  Stuff-Stash/client/src/components/CreateOrg.jsx
  Stuff-Stash/client/src/components/RenameOrg.jsx
  Stuff-Stash/client/src/components/StockRoomViewDashboard.jsx
  Stuff-Stash/client/src/components/UserProfile.jsx
  Stuff-Stash/client/src/components/blah.jsx
  Stuff-Stash/client/src/components/orgView.jsx
  Stuff-Stash/client/src/components/registrationform.jsx
  Stuff-Stash/client/src/components/welcome2.jsx
  Stuff-Stash/client/src/index.js
Labels: Maintenance

#69 60 asset cards matt lynaa
  Stuff-Stash/client/src/App.js
  Stuff-Stash/client/src/Pages/dashboard.js
  Stuff-Stash/client/src/Pages/styles/dashboardStyles.css
  Stuff-Stash/client/src/components/assetCard.jsx
  Stuff-Stash/client/src/components/styles/assetCard.css
Labels: enhancement, Feature, Frontend, sprint3

#71 feature: Creating an organization adds user to organization
  Stuff-Stash/client/package-lock.json
  Stuff-Stash/client/package.json
  Stuff-Stash/client/src/components/CreateOrg.jsx
  Stuff-Stash/server/index.js
Labels: Feature, Backend, sprint3

#70 50 reformat user box on dashboard lynaa madeline
  Stuff-Stash/client/src/Pages/styles/dashboardStyles.css
  Stuff-Stash/client/src/components/UserProfile.jsx
Labels: enhancement, Frontend, sprint3
